apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      name: hello-web
      labels:
        app: hello
    spec:
      containers:
      - name: flask
        image: pn2d/hello-web:v1
        ports:
        - name: http
          containerPort: 80
