kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hello-db
spec:
  serviceName: hello-db
  replicas: 1
  selector:
    matchLabels:
      app: hello
      what: db
  template:
    metadata:
      name: hello-db
      labels:
        app: hello
        what: db
    spec:
      containers:
      - name: mysql
        image: percona:5
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        - name: MYSQL_DATABASE
          value: hellodb
        - name: MYSQL_USER
          value: hello_user
        - name: MYSQL_PASSWORD
          value: "aaa"
        volumeMounts:
        - name: hello-db-data
          mountPath: "/var/lib/mysql"
        args:
            - '--datadir=/var/lib/mysql'
            - '--ignore-db-dir=lost+found'
      initContainers:
      - name: chown-datadir
        image: busybox
        command: ['sh', '-c', 'chown 999:999 /mnt/mysql-data']
        volumeMounts:
        - name: hello-db-data
          mountPath: "/mnt/mysql-data"

  volumeClaimTemplates:
  - metadata:
      name: hello-db-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: hello-db
spec:
  selector:
    app: hello
    what: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None # žádný load balancing, jenom udělá DNS
