#!/bin/bash
dir=$(cd $(dirname $0) && pwd)

exec docker run -ti --rm \
    -e CLOUDSDK_CONFIG=/config/mygcloud \
    -v ${dir}/_gcloud/config:/config/mygcloud \
    -v ${dir}/_gcloud/certs:/certs \
    -v ${dir}/k8s:/k8s \
    -v ${dir}/setup-scripts:/setup-scripts \
    google/cloud-sdk /bin/bash
