apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: reset-counter
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: reset-counter
              image: pn2d/hello-backend:v3
              command: ["python3", "/app/reset.py"]
              env:
                - name: MYSQL_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: hello-config
                      key: db.host
                - name: MYSQL_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: hello-config
                      key: db.database
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: hello-db-passwords
                      key: username
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: hello-db-passwords
                      key: password
