apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      name: hello-web
      labels:
        app: hello-web
    spec:
      containers:
      - name: flask
        image: gcr.io/hello-minikube-zero-install/hello-node
        ports:
        - name: http
          containerPort: 8080
