kind: Service
apiVersion: v1
metadata:
  name: hello-loadbalancer
spec:
  selector:
    app: hello-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "X.X.X.X"
