apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      what: frontend
  template:
    metadata:
      name: hello-web
      labels:
        app: hello
        what: frontend
    spec:
      containers:
      - name: flask
        image: pn2d/hello-web:v2
        ports:
        - name: http
          containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://hello-backend/backend"
        livenessProbe:
          httpGet:
            path: /alive
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 1
          failureThreshold: 1
