apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      what: frontend
  template:
    metadata:
      name: hello-web
      labels:
        app: hello
        what: frontend
    spec:
      containers:
      - name: flask
        image: pn2d/hello-web:v2
        ports:
        - name: http
          containerPort: 80
        env:
          - name: BACKEND_URL
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: backend.url
        livenessProbe:
          httpGet:
            path: /alive
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: hello-loadbalancer
spec:
  selector:
    app: hello
    what: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
