apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      what: backend
  template:
    metadata:
      name: hello-backend
      labels:
        app: hello
        what: backend
    spec:
      containers:
      - name: backend
        image: pn2d/hello-backend:v2
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
          - name: MYSQL_HOST
            value: hello-db
          - name: MYSQL_DATABASE
            value: hellodb
          - name: MYSQL_USER
            value: hello_user
          - name: MYSQL_PASSWORD
            value: "aaa"
