apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
      what: backend
  template:
    metadata:
      name: hello-backend
      labels:
        app: hello
        what: backend
    spec:
      containers:
      - name: backend
        image: pn2d/hello-backend:v2
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: db.host
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: hello-config
                key: db.database
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: hello-db-passwords
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hello-db-passwords
                key: password
